name: workflow à réutiliser

on:
  # Définir ce workflow comme réutilisable par d'autres workflows
  workflow_call:
    outputs:
      variable1:
        description: premier output
        value: ${{ jobs.job1.outputs.sortie1 }}
      variable2:
        description: deuxième output
        value: ${{ jobs.job1.outputs.sortie2 }}

jobs:
  job1:
    name: Générer des outputs
    runs-on: ubuntu-latest
    outputs:
      sortie1: ${{ steps.etape1.outputs.VAR1 }}
      sortie2: ${{ steps.etape2.outputs.VAR2 }}
    steps:
      - name: Set VAR1
        id: etape1
        run: echo "VAR1=Hello" >> $GITHUB_OUTPUT

      - name: Set VAR2
        id: etape2
        run: echo "VAR2=World" >> $GITHUB_OUTPUT

      - name: Echo VAR1 et VAR2
        run: echo ${{ steps.etape1.outputs.VAR1 }} ${{ steps.etape2.outputs.VAR2 }}

  job2:
    name: Récupérer les paramètres du 1er job
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Echo sortie1 et sortie2
        run: echo ${{ needs.job1.outputs.sortie1 }} ${{ needs.job1.outputs.sortie2 }}


