name: Workflow d'issue

on:
  issues:
    types:
      - opened

jobs:
  commentaire:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Réponse à l'auteur de l'issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
            -X POST \
            -d '{"body":"Bonjour @'${ISSUE_AUTHOR}',\n\nNous avons bien pris en compte votre souci : **'${ISSUE_TITLE}'**. Nous allons y jeter un oeil."}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments
